---
name: 'Zoom'
configurationClass:
  name: 'ZoomConfiguration'
  package: 'com.exclamationlabs.connid.base.zoom.configuration'
rest: true # io-error-retries
service: true # service-url
results: true
security:
  authenticator:
    oauth2ClientCredentials: true
custom:
  items:
    required:
      accountId:
        type: string
        order: 701
        display: 'Zoom Account Id'
        help: 'Zoom Account Id required for authentication.'
    optional:
      userDeactivationEnabled:
        type: boolean
        order: 3010
        default: 'false'
        display: 'Deactivate On Delete Enabled'
        help: 'If true, a request to delete a Zoom user will instead deactivate the user on Zoom.'
      deactivateOnDelete:
          type: boolean
          order: 3020
          default: 'true'
          display: 'Deactivate On Delete'
          help: 'If true, a request to delete a Zoom user will instead deactivate the user on Zoom.'
      disassociateOnDelete:
        type: boolean
        order: 3030
        default: 'false'
        display: 'Disassociate On Delete'
        help: 'If true, a request to delete a Zoom user will instead disassociate the users email into an independent Zoom Account.'
      immediateLogoutOnDeactivate:
        type: boolean
        order: 3040
        default: 'false'
        display: 'Immediate Logout on Deactivate'
        help: 'If true, a SSO logout via Zoom API will also be executed when a user is deactivated.'

