---
name: 'Zoom'
configurationClass:
  name: 'ZoomConfiguration'
  package: 'com.exclamationlabs.connid.base.zoom.configuration'
rest: true # io-error-retries
service: true # service-url
results: true
security:
  authenticator:
    oauth2ClientCredentials: true
custom:
  items:
    required:
      accountId:
        type: string
        order: 701
        display: 'Zoom Account Id'
        help: 'Zoom Account Id required for authentication.'


